### PR TITLE
Added support for user defined templated for displaying the errors.

### PR DESCRIPTION
**Pull request by razvanz**
Added support for user defined templated for displaying the errors. Updated readme.md. Bump version to 1.4.3. And removed useless white spaces.

### CODE REVIEW

**Comment by CWSpear** [comment]
So generally, adding yourself as an author, changing the name of the project in Bower and pointing it to your another URL is generally considered very rude. I undid those changes.

I also cleaned up your code formatting and the examples. For future PRs, please be more mindful to be consistent as possible with the author's style (i.e. spaces v. tab and such).

**Comment by razvanz** [comment]
I guess you are talking about this one: https://github.com/razvanz/angular-form-errors

If you have a closer look it is not just changing the name and the bower reference. I used your template but I have changed most of the implementation. I thought that you are not interested in my implementation so that's why I created a new project.

Basically I changed the directives and the way the errors get to be displayed. It's because, in my apllication,  I need the errors to be propagated to other views. Therefore the implementation is using angular events to propagate the form(s) errors from the `$rootscope` downwards. This makes it possible to display them anywhere in the app rather than just the bottom of the form. 

I don't think is rude since it's a different implementation. Your license states:

> rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software
> and I just added myself as an author,  but kept you as well. Also I left a reference for your original project.

Have a look at it and if you are interested to change your original project to this implementation I am willing to remove my project and use yours.

PS: Now I saw that it was the forked repository that also had bower, name, authors changed. Sorry about that. Before creating the new repository I started making changes on the fork, but as I earlier said, I thought you will not be interested so I created a new repository. I just forgot to revert the commits.

**Comment by CWSpear** [comment]
You created a Pull Request that changed that stuff. That's what I was specifically referring to. As in if I had used the "Merge Pull Request" button in GitHub, it would have changed all that stuff in Bower.

You _are_ fine to fork. And I specifically said I would consider your PR. I said _twice_ I would consider your PR and never indicated otherwise, so I don't even know where you got the idea that I wouldn't.

Anyway, I merged that functionality, mentioned you as a contributor, but reverted the changes in `bower.json`.

**Comment by CWSpear** [comment]
I see your edit. Just as a tip for future references, the easiest way to do a PR is to create a separate branch just for that PR. And then any changes you make to that branch are automatically included in the PR (as you've discovered). So if it's a separate branch, you can continue make other changes to other branches (i.e. `master`/`gh-pages`) without affecting the PR. It makes things a lot easier to manage all around.

**Pull request merged**
